NB_CHANNELS = 5
SAMPLING_RATE = 256

MUSE_SCAN_TIMEOUT = 10.5
AUTO_DISCONNECT_DELAY = 3

LSL_SCAN_TIMEOUT = 2 # How long to look for an LSL stream.
LSL_CHUNK = 12 # Chunk size.
LSL_BUFFER = 360 # Buffer length.

VIEW_SUBSAMPLE = 2
VIEW_BUFFER = 12