name: Test

on:
  push:
    branches: [ master, 'dev/*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.os }}, py-${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macOS-latest]
        python_version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install Linux dependencies
      if: "startsWith(runner.os, 'Linux')"
      run: |
        python -m pip install --upgrade pip wheel

        # Install wxPython wheels since they are distribution-specific and therefore not on PyPI
        # See: https://wxpython.org/pages/downloads/index.html
        pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython

        pip install .
    - name: Install MacOS/Windows dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install .

  typecheck:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        pip install .
        pip install mypy
    - name: Typecheck
      run: |
        python -m mypy
